### PR TITLE
fix form generation for hhvm

### PR DESCRIPTION
**Pull request by zkiiito**
get_declared_classes() with array_diff() to detect newly declared classes properly

### CODE REVIEW

**Comment by zkiiito** [comment]
with this commit, many failing cases are fixed in the symfony1 tests on hhvm

**Comment by j0k3r** [comment]
Looks good 👍

**Comment by zkiiito** [comment]
could you please re-run this test?:
https://travis-ci.org/LExpress/symfony1/jobs/131954644

**Comment by j0k3r** [comment]
Done, still the problem related to APC

**Comment by zkiiito** [comment]
yeah, but the solution is on it's way for that:
https://reviews.facebook.net/D58479 

and i'm working on the first two "dubious" cases :)

**Pull request merged**
